/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bbb0a140-e6bd-40b1-b0f6-8d0dc768e42a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_CBMMoPs6T",
    "aws_user_pools_web_client_id": "1vo22lk12b9qvatvtnnba9npe0",
    "oauth": {}
};


export default awsmobile;
